CREATE TABLE CAR_INFO
(
	MODEL_NUM INT PRIMARY KEY AUTO_INCREMENT, #모델넘버(PX)
	MODEL_NAME VARCHAR(20) NOT NULL, #모델명
	CAR_PRICE INT NOT NULL DEFAULT 0, #가격
	MAKER_NAME VARCHAR(30) NOT NULL #제조사
);	

CREATE TABLE SALES_INFO
(
	BUY_NUM INT PRIMARY KEY AUTO_INCREMENT, #판매번호
	BUY_NAME VARCHAR(20) NOT NULL, #구매자명
	CONTACT_NUM VARCHAR(30), #구매자 연락처
	COLOR_NAME VARCHAR(10) NOT NULL, #색상#
	BUY_DATE DATETIME DEFAULT SYSDATE(), #판매일
	MODEL_NUM INT REFERENCES CAR_INFO (MODEL_NUM) #모델번호(FX)
);

SELECT * FROM car_info;
SELECT * FROM sales_info;

#DELETE FROM car_info WHERE MODEL_NUM = '6';
#DELETE FROM sales_info WHERE MODEL_NUM IS NULL;
#COMMIT;
SELECT DISTINCT MODEL_NAME FROM car_info;
#ROLLBACK;

#INSERT INTO SALES_INFO (BUY_NAME, COLOR_NAME, CONTACT_NUM, MODEL_NUM ) VALUES ("김자바", "레드", "", 
#(SELECT MODEL_NUM FROM car_info WHERE MODEL_NAME = '아반떼') );

    SELECT
        s.BUY_NUM,
        s.BUY_NAME,
        s.COLOR_NAME,
        s.CONTACT_NUM,
        s.MODEL_NUM,
        TO_CHAR(s.BUY_DATE, 'YYYY.MM.DD HH24:MI') AS BUY_DATE,
        c.MODEL_NAME,
        c.MAKER_NAME,
        c.CAR_PRICE
    FROM SALES_INFO s
    INNER JOIN CAR_INFO c
    ON s.MODEL_NUM = c.MODEL_NUM
    ORDER BY s.BUY_DATE DESC;