CREATE TABLE CAR_INFO
(
	MODEL_NUM INT PRIMARY KEY AUTO_INCREMENT, #모델넘버(PX)
	MODEL_NAME VARCHAR(20), #모델명
	CAR_PRICE INT, #가격
	MAKER_NAME VARCHAR(30) UNIQUE #제조사
);	

CREATE TABLE SALES_INFO
(
	BUY_NUM INT PRIMARY KEY AUTO_INCREMENT, #판매번호
	BUY_NAME VARCHAR(20), #구매자명
	CONTACT_NUM VARCHAR(30), #구매자 연락처
	COLOR_NAME VARCHAR(10) UNIQUE, #색상#
	BUY_DATE DATETIME DEFAULT SYSDATE(), #판매일
	MODEL_NUM INT REFERENCES CAR_INFO (MODEL_NUM) #모델번호(FX)
);

